platform :ios, '14.0'  # iOS 최소 버전 12.0으로 설정

# React Native와 react-native-permissions 스크립트 로드
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

target 'MemoryStorage' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 필요한 권한 추가 (react-native-permissions 권한 설정)
  setup_permissions([
    'Camera',
    'PhotoLibrary',
  ])

  target 'MemoryStorageTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end